"""
Word document generator for architecture diagrams.
Creates professional .docx documentation with embedded diagrams.
"""
import os
from datetime import datetime
from typing import Optional, Tuple, List
from io import BytesIO

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.table import WD_TABLE_ALIGNMENT

from core.logging import get_logger
from services.sessions import session_manager
from utils import get_latest_files

logger = get_logger("docx_generator")


def create_architecture_document(
    session_id: str,
    title: Optional[str] = None,
    author: Optional[str] = "Diagram Agent"
) -> Tuple[bool, bytes, str]:
    """
    Generate a professional Word document for an architecture diagram.
    
    Args:
        session_id: The diagram session ID
        title: Optional custom title (defaults to session description)
        author: Document author name
        
    Returns:
        Tuple of (success, document_bytes, filename)
    """
    session = session_manager.get_session(session_id)
    if not session:
        logger.error(f"Session not found: {session_id}")
        return False, b"", ""
    
    if not session.current_base_filename:
        logger.error(f"No diagram found for session: {session_id}")
        return False, b"", ""
    
    # Get diagram files
    files = get_latest_files(session.current_base_filename)
    if "png" not in files:
        logger.error(f"No PNG diagram found for session: {session_id}")
        return False, b"", ""
    
    try:
        doc = Document()
        
        # Set up document properties
        doc.core_properties.author = author
        doc.core_properties.created = datetime.now()
        doc.core_properties.title = title or session.diagram_description or "Architecture Diagram"
        
        # Create styles
        _setup_styles(doc)
        
        # Title Page
        _add_title_page(doc, title or session.diagram_description, author)
        
        # Table of Contents placeholder
        doc.add_page_break()
        _add_table_of_contents(doc)
        
        # Architecture Overview
        doc.add_page_break()
        _add_architecture_section(doc, session, files["png"])
        
        # Component Details (from conversation)
        _add_components_section(doc, session)
        
        # Design Decisions
        _add_design_decisions(doc, session)
        
        # Appendix: Python Code
        doc.add_page_break()
        _add_code_appendix(doc, session)
        
        # Save to bytes
        buffer = BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        
        filename = f"{session.current_base_filename}_documentation.docx"
        logger.info(f"Generated documentation: {filename}")
        
        return True, buffer.read(), filename
        
    except Exception as e:
        logger.error(f"Failed to generate document: {e}")
        return False, b"", ""


def _setup_styles(doc: Document):
    """Set up custom styles for the document."""
    styles = doc.styles
    
    # Heading 1 style customization
    h1_style = styles['Heading 1']
    h1_style.font.size = Pt(24)
    h1_style.font.bold = True
    h1_style.font.color.rgb = RGBColor(0, 51, 102)
    
    # Heading 2 style
    h2_style = styles['Heading 2']
    h2_style.font.size = Pt(18)
    h2_style.font.bold = True
    h2_style.font.color.rgb = RGBColor(0, 76, 153)


def _add_title_page(doc: Document, title: str, author: str):
    """Add a professional title page."""
    # Add spacing at top
    for _ in range(6):
        doc.add_paragraph()
    
    # Title
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title_para.add_run(title or "Architecture Documentation")
    title_run.bold = True
    title_run.font.size = Pt(36)
    title_run.font.color.rgb = RGBColor(0, 51, 102)
    
    # Subtitle
    doc.add_paragraph()
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = subtitle.add_run("Technical Architecture Document")
    sub_run.font.size = Pt(18)
    sub_run.font.color.rgb = RGBColor(102, 102, 102)
    
    # Add more spacing
    for _ in range(8):
        doc.add_paragraph()
    
    # Author and date
    info = doc.add_paragraph()
    info.alignment = WD_ALIGN_PARAGRAPH.CENTER
    info_run = info.add_run(f"Generated by: {author}\n")
    info_run.font.size = Pt(12)
    
    date_run = info.add_run(f"Date: {datetime.now().strftime('%B %d, %Y')}")
    date_run.font.size = Pt(12)


def _add_table_of_contents(doc: Document):
    """Add table of contents section."""
    doc.add_heading("Table of Contents", level=1)
    
    toc_items = [
        ("1. Architecture Overview", 3),
        ("2. Component Details", 4),
        ("3. Design Decisions", 5),
        ("4. Appendix: Source Code", 6)
    ]
    
    for item, page in toc_items:
        para = doc.add_paragraph()
        para.add_run(item)
        # Add tab and page number
        para.add_run("\t" * 10 + str(page))


def _add_architecture_section(doc: Document, session, png_path: str):
    """Add the architecture overview section with embedded diagram."""
    doc.add_heading("1. Architecture Overview", level=1)
    
    # Description
    if session.diagram_description:
        doc.add_paragraph(session.diagram_description)
    
    doc.add_paragraph()
    
    # Embedded diagram
    doc.add_heading("Architecture Diagram", level=2)
    
    try:
        # Add the diagram image, scaled to fit page width
        doc.add_picture(png_path, width=Inches(6.5))
        
        # Center the image
        last_paragraph = doc.paragraphs[-1]
        last_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Caption
        caption = doc.add_paragraph()
        caption.alignment = WD_ALIGN_PARAGRAPH.CENTER
        caption_run = caption.add_run(f"Figure 1: {session.diagram_description or 'Architecture Diagram'}")
        caption_run.italic = True
        caption_run.font.size = Pt(10)
        
    except Exception as e:
        logger.warning(f"Could not embed diagram image: {e}")
        doc.add_paragraph("[Diagram image could not be embedded]")


def _add_components_section(doc: Document, session):
    """Add component details extracted from conversation."""
    doc.add_heading("2. Component Details", level=1)
    
    doc.add_paragraph(
        "This section describes the key components of the architecture "
        "and their roles in the system."
    )
    
    # Extract components from conversation history
    components = _extract_components_from_history(session)
    
    if components:
        # Create a table for components
        table = doc.add_table(rows=1, cols=3)
        table.style = 'Table Grid'
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        
        # Header row
        header_cells = table.rows[0].cells
        header_cells[0].text = "Component"
        header_cells[1].text = "Type"
        header_cells[2].text = "Purpose"
        
        # Make header bold
        for cell in header_cells:
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.bold = True
        
        # Add component rows
        for comp in components[:15]:  # Limit to 15 components
            row_cells = table.add_row().cells
            row_cells[0].text = comp.get("name", "")
            row_cells[1].text = comp.get("type", "")
            row_cells[2].text = comp.get("purpose", "")
    else:
        doc.add_paragraph(
            "Component details will be populated based on the architecture design."
        )


def _extract_components_from_history(session) -> List[dict]:
    """Extract component information from session history."""
    components = []
    
    if not session.last_generated_code:
        return components
    
    # Parse component definitions from code
    import re
    
    # Find variable assignments with diagram classes
    pattern = r'(\w+)\s*=\s*(\w+)\s*\(\s*["\']([^"\']+)["\']\s*\)'
    matches = re.findall(pattern, session.last_generated_code)
    
    for var_name, class_name, label in matches:
        if class_name not in ['Diagram', 'Cluster', 'Edge']:
            components.append({
                "name": label,
                "type": class_name,
                "purpose": _infer_purpose(class_name)
            })
    
    return components


def _infer_purpose(class_name: str) -> str:
    """Infer component purpose from class name."""
    purposes = {
        "EC2": "Compute instance",
        "S3": "Object storage",
        "RDS": "Relational database",
        "Lambda": "Serverless function",
        "VPC": "Virtual private network",
        "ALB": "Load balancer",
        "CloudWatch": "Monitoring",
        "BigQuery": "Data warehouse",
        "GKE": "Kubernetes cluster",
        "Pub/Sub": "Message queue",
        "Server": "Compute node",
        "Firewall": "Network security",
    }
    
    for key, purpose in purposes.items():
        if key.lower() in class_name.lower():
            return purpose
    
    return "Infrastructure component"


def _add_design_decisions(doc: Document, session):
    """Add design decisions section."""
    doc.add_heading("3. Design Decisions", level=1)
    
    doc.add_paragraph(
        "This section documents the key design decisions made during the architecture design process."
    )
    
    # Extract from conversation history if available
    if session.conversation_history:
        doc.add_heading("Conversation History", level=2)
        
        for msg in session.conversation_history[-10:]:  # Last 10 messages
            role = msg.get("role", "unknown").capitalize()
            content = msg.get("content", "")
            
            if len(content) > 300:
                content = content[:300] + "..."
            
            para = doc.add_paragraph()
            role_run = para.add_run(f"{role}: ")
            role_run.bold = True
            para.add_run(content)
    else:
        doc.add_paragraph("No conversation history available.")


def _add_code_appendix(doc: Document, session):
    """Add appendix with the Python source code."""
    doc.add_heading("4. Appendix: Source Code", level=1)
    
    doc.add_paragraph(
        "The following Python code was used to generate the architecture diagram "
        "using the 'diagrams' library."
    )
    
    if session.last_generated_code:
        # Add code in a monospace style
        code_para = doc.add_paragraph()
        code_para.style = 'No Spacing'
        
        # Split code into lines and add each line
        for line in session.last_generated_code.split('\n'):
            code_run = code_para.add_run(line + '\n')
            code_run.font.name = 'Courier New'
            code_run.font.size = Pt(9)
    else:
        doc.add_paragraph("[No source code available]")
